service: serverless-webpack-typescript-example
frameworkVersion: "3"
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true
